version: "3.9"


services:
  mysql-db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: meusecret123
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

  wordpress:
    image: wordpress:5.1.1-fpm-alpine
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql-db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: aquelasenhatop
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mysql-db
    networks:
      - my-network

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - nginx:/etc/nginx/conf.d
    depends_on:
      - wordpress
    networks:
      - my-network

volumes:
  db-data:
  wordpress:
  nginx:

networks:
  my-network:
    driver: bridge
